### ISSUE TITLE
Improve error message when mjml is not installed

### ISSUE THREAD

**Issue by nicolas-brousse** [m-basov/mjml-ruby#12]
In a server I've got an issue where mails was not sent anymore. 

We've got the following error, because `mjml` was not installed (it was before):
```
ActionView::Template::Error
No such file or directory - 
```

I think [`#extract_executable_version`](https://github.com/kolybasov/mjml-ruby/blob/master/lib/mjml.rb#L43) method needs to catch `Errno::ENOENT` exception, or something like that.

It may help a lot for debug.

In our case, on each deploys packages are installed. But some server changes made that `yarn install` doesn't installed `mjml`.  
For me the main issue here was that the error message came from ActionMailer and not MJML gem.

**Comment by m-basov** [comment]
@nicolas-brousse thank you for pointing this out! I do not have time to work on this project yet so if you can make PR with better error it may help someone in the future! :)

**Comment by nicolas-brousse** [comment]
@kolybasov I'll try to have a look and open a PR this week if I found a bit of time
