### ISSUE TITLE
extract_executable_version with --version instead of -V

### ISSUE THREAD

**Issue by mmichaa** [m-basov/mjml-ruby#14]
We are using MJML v4.4.1 with NodeJS v10.16.0 in a Rails project. For some reason the `#extract_executable_version` doesn't work for us with `-V` but it works with `--version`.

https://github.com/kolybasov/mjml-ruby/blob/ae086c652ece50f0cf1d12038b8f0b029650d884/lib/mjml.rb#L46

Maybe it's an issue when using newer versions of MJML or NodeJS?

Sorry for this bad and short error report, but hopefully it's still acceptable.

**Comment by m-basov** [comment]
@mmichaa thanks for the report. I just published [v0.3.4](https://rubygems.org/gems/mjml-ruby/versions/0.3.4). Please let me know if it fixed the problem.

**Comment by mmichaa** [comment]
@kolybasov, thank you very much! I'm will try to test it today.

**Comment by mmichaa** [comment]
@kolybasov, the new version fixed the problem for us. Thank you very much!
