### ISSUE TITLE
ROOT_TAGS_REGEX fails to recognise mjml tag with attributes

### ISSUE THREAD

**Issue by samstickland** [m-basov/mjml-ruby#18]
This is the opening MJML tag I get from a Passport export `<mjml owa="desktop" version="4.5.1">`

`ROOT_TAGS_REGEX` is `/<mjml>.*<\/mjml>/mi` so it fails to match.

**Comment by samstickland** [comment]
Can we change the regex to this?

```ROOT_TAGS_REGEX = %r{<mjml((\s+\w+(\s*=\s*(?:".*?"|'.*?'|[\^'">\s]+))?)+\s*|\s*)/?>.*<\/mjml>}im```

(based on https://haacked.com/archive/2004/10/25/usingregularexpressionstomatchhtml.aspx/)

**Comment by samstickland** [comment]
Actually there might be more general compatibility issues with MJML v4?

**Comment by m-basov** [comment]
@samstickland I believe we might use something simpler for matching root tag because we don't care about the attributes. So something like `<mjml`[any symbol]`>` should do the work.I will gladly accept the PR with it if you want to help 😃

**Comment by m-basov** [comment]
@samstickland actually, it was pretty fast to fix, sorry for the late response. Please let me know if you will have any issues with MJML v4 and even better – submit the PR, they are greatly appreciated :)
