### ISSUE TITLE
Broken in ActionMailer Preview after Rails 6.0.3 upgrade

### ISSUE THREAD

**Issue by kjf** [m-basov/mjml-ruby#19]
Hi,

Thanks so much for the work on this gem. It's been incredibly useful.

I've run into an issue after upgrading my app from Rails 6.0.2.2 to 6.0.3. When working with Rails ActionMailer Previews my MJML templates are no longer transformed into HTML. Instead the template is output as raw MJML.

Everything is still working outside of Previews.

**Comment by kjf** [comment]
Apologies, this was a stupid mistake on my side. I had generated a new mailer and since `view/layouts/mailer.html.erb` had been renamed to `view/layouts/mailer.html.mjml` rails generated a new `mailer.html.erb` which was overriding the `MJML` version. 🤦

**Comment by m-basov** [comment]
@kjf hi! Glad you were able to resolve your issue! Feel free to submit any issues(even better PRs) if you discover any incompatibilities!

**Comment by DavertMik** [comment]
Thanks @kjf 
Your comment saved me an evening. I didn't notice Rails regenerated this layout as well
