### ISSUE TITLE
Update version 4 regex to work with version 4.xx.x

### ISSUE THREAD

**Issue by jwoodrow** [m-basov/mjml-ruby#25]
`VERSION_4_REGEX = /^mjml-cli: (\d\.\d\.\d)/I`

current regex cannot match the `4.10.1` version of `mjml-cli` which means the gem will keep saying the executable is not found when it actually is

**Comment by m-basov** [comment]
Thanks for the report! Fixed in https://rubygems.org/gems/mjml-ruby/versions/0.4.1
