### ISSUE TITLE
Checking mjml executable on each rendering make every rendering very slow

### ISSUE THREAD

**Issue by vddgil** [m-basov/mjml-ruby#3]
You seems to run the `find_executable` method on each render which make rendering very slow for an email with a lot of partials (Almost 7s for me)

Is there a way to memoize this or do that at the gem initialization ?

Thanks in advance !

**Comment by m-basov** [comment]
@vddgil sorry, just saw that version of mjml is checking on every `Parser` instantiate. I bumped version of gem to 0.2.3 with fix for it. Let me know result please!

**Comment by vddgil** [comment]
Awesome ! Thanks a lot it's really faster now ;)
