### ISSUE TITLE
Previewing emails with ActionMailer::Preview doesn't parse MJML

### ISSUE THREAD

**Issue by mavericohm** [m-basov/mjml-ruby#5]
Hi,

When we run an email with a pure `ActionMailer`, `mjml-ruby` works as expected.

On the other side, when we execute our emails via `ActionMailer::Preview`, the mjml is simply not parsed, but we can see the email in plain text. For example, when we visit: `http://localhost:3001/rails/mailers/weekly_mailer/index`

We are not sure whether this is an issue of our implementation or if there is an issue with `mjml-ruby` not working with `ActionMailer::Preview`. Could you clarify/confirm whether `mjml-ruby` should work `with ActionMailer::Preview` or not?

Thank you!

**Comment by m-basov** [comment]
Hello @raulsann,

thanks for the noticed issue. I never tried to use `ActionMailer::Preview` with this gem. So I need to look where is problem. For now I can suggest to use [letter_opener](https://github.com/ryanb/letter_opener) and maybe [letter_opener_web](https://github.com/fgrehm/letter_opener_web) if you use remote server or docker.

**Comment by mavericohm** [comment]
Thank you for the quick reply @kolybasov. At the moment we are using https://github.com/mjmlio/gulp-mjml to work around this issue.

**Comment by mavericohm** [comment]
However, because the parser of mjml does not work well with ERB, we need to be constantly looking a workaround to render mjml elements. This is one example: https://github.com/mjmlio/mjml/issues/427#issuecomment-255735501

**Comment by m-basov** [comment]
Hello @raulsann. There are example repo with `ActionMailer::Preview` https://github.com/kolybasov/actionmailer_preview_mjml_test and it is working as expected.
But I tested with Rails 5. What Rails version do you use?

Provide please example repository with mailer issue. It will help to understand your problem. Thanks.

**Comment by m-basov** [comment]
`mjml-ruby` is working with `ActionMailer::Preview` so I am closing this issue. https://github.com/mjmlio/mjml/issues/427#issuecomment-257343529
