### ISSUE TITLE
Old dry-configurable dependency causes clashes

### ISSUE THREAD

**Issue by alekseyg** [m-basov/mjml-ruby#9]
I have a project that uses `dry-validation` which is also dependent on `dry-configurable`, but it uses version 0.4.0 (0.7.0 is out by now). I tried testing what happens when I bump the version in a fork and it seems to work great. Is there a way we could test the gem with other versions of `dry-configurable` and allow a greater range of versions or to remove the dependency altogether?

**Comment by m-basov** [comment]
@alekseyg we can list `dry-configurable` dependency as `dry-validation` listed it.

And replace this line:
https://github.com/kolybasov/mjml-ruby/blob/master/mjml-ruby.gemspec#L21

```ruby
s.add_runtime_dependency 'dry-configurable', '~> 0.3'
```

with:

```ruby
spec.add_runtime_dependency 'dry-configurable', '~> 0.1', '>= 0.1.3'
```

Do you mind to send PR for this?
Thanks!

**Comment by alekseyg** [comment]
That works great with my project. PR sent. :)

**Comment by m-basov** [comment]
[Released!](https://github.com/kolybasov/mjml-ruby/tree/v0.3.1) Thanks!
